# openapi2-functions.yaml
swagger: '2.0'
host: "bls-0hb1l9hf489ye.apigateway.hs-research-tumgoren.cloud.goog "
x-google-endpoints:
- name: "bls-0hb1l9hf489ye.apigateway.hs-research-tumgoren.cloud.goog"
  allowCors: True
info:
  title: BLS county-unemployment
  description: Unemployment data by county.
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /county_unemployment:
    get:
      summary: Get BLS county unemployment data.
      parameters:
        - in: path
          name: county
          type: string
          required: true
          description: Name of county, e.g. Sacramento County
        - in: path
          name: state
          type: string
          required: true
          description: State postal code, e.g. CA
      operationId: county_unemployment
      x-google-backend:
        address: https://us-west2-hs-research-tumgoren.cloudfunctions.net/bls_apikey
      security:
      - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"